curator: Charlotte
goal: Manage Data in Your Application 
checkpoints: 
  - task: Learn about State 
    resource-url: "https://www.toptal.com/react/managing-view-state-with-react/"
  - task: Store Your States
    resource-url: "https://www.youtube.com/watch?v=5tT8FXeE1Y8/"
  - task: Handle State Changes
    resource-url: "http://reactkungfu.com/2016/03/dive-into-react-codebase-handling-state-changes/"
